# Generated by Django 5.1.2 on 2024-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
